# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_mate/product_search_engine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_mate import product_common_pb2 as grpc__mate_dot_product__common__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_mate/product_search_engine.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\030io.datanerd.generated.esP\001Z\010datanerd'),
  serialized_pb=_b('\n%grpc_mate/product_search_engine.proto\x1a\x1egrpc_mate/product_common.proto\x1a\x1cgoogle/api/annotations.proto\"|\n\x15UploadProductResponse\x12:\n\rresult_status\x18\x01 \x01(\x0e\x32#.UploadProductResponse.ResultStatus\"\'\n\x0cResultStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"1\n\x1b\x44ownloadProductImageRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\"+\n\x17\x44ownloadProductsRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"8\n\x15SearchProductsRequest\x12\x10\n\x08key_word\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"4\n\x16SearchProductsResponse\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product\"I\n\x1d\x43\x61lculateProductScoreResponse\x12\x19\n\x07product\x18\x01 \x01(\x0b\x32\x08.Product\x12\r\n\x05score\x18\x02 \x01(\x03\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04ping\x18\x01 \x01(\t\"\x1c\n\x0c\x45\x63hoResponse\x12\x0c\n\x04pong\x18\x02 \x01(\t2M\n\x14ProductUpdateService\x12\x35\n\rUploadProduct\x12\x08.Product\x1a\x16.UploadProductResponse\"\x00(\x01\x32\xa4\x02\n\x12ProductReadService\x12:\n\x10\x44ownloadProducts\x12\x18.DownloadProductsRequest\x1a\x08.Product\"\x00\x30\x01\x12\x43\n\x0eSearchProducts\x12\x16.SearchProductsRequest\x1a\x17.SearchProductsResponse\"\x00\x12G\n\x15\x43\x61lculateProductScore\x12\x08.Product\x1a\x1e.CalculateProductScoreResponse\"\x00(\x01\x30\x01\x12\x44\n\x14\x44ownloadProductImage\x12\x1c.DownloadProductImageRequest\x1a\n.DataChunk\"\x00\x30\x01\x32P\n\x0b\x45\x63hoService\x12\x41\n\x04\x45\x63ho\x12\x0c.EchoRequest\x1a\r.EchoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x11/grpc/api/v1/echo:\x01*B&\n\x18io.datanerd.generated.esP\x01Z\x08\x64\x61tanerdb\x06proto3')
  ,
  dependencies=[grpc__mate_dot_product__common__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])



_UPLOADPRODUCTRESPONSE_RESULTSTATUS = _descriptor.EnumDescriptor(
  name='ResultStatus',
  full_name='UploadProductResponse.ResultStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=227,
)
_sym_db.RegisterEnumDescriptor(_UPLOADPRODUCTRESPONSE_RESULTSTATUS)


_UPLOADPRODUCTRESPONSE = _descriptor.Descriptor(
  name='UploadProductResponse',
  full_name='UploadProductResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_status', full_name='UploadProductResponse.result_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPLOADPRODUCTRESPONSE_RESULTSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=227,
)


_DOWNLOADPRODUCTIMAGEREQUEST = _descriptor.Descriptor(
  name='DownloadProductImageRequest',
  full_name='DownloadProductImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='DownloadProductImageRequest.product_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=278,
)


_DOWNLOADPRODUCTSREQUEST = _descriptor.Descriptor(
  name='DownloadProductsRequest',
  full_name='DownloadProductsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='DownloadProductsRequest.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=323,
)


_SEARCHPRODUCTSREQUEST = _descriptor.Descriptor(
  name='SearchProductsRequest',
  full_name='SearchProductsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_word', full_name='SearchProductsRequest.key_word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='SearchProductsRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=381,
)


_SEARCHPRODUCTSRESPONSE = _descriptor.Descriptor(
  name='SearchProductsResponse',
  full_name='SearchProductsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='products', full_name='SearchProductsResponse.products', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=435,
)


_CALCULATEPRODUCTSCORERESPONSE = _descriptor.Descriptor(
  name='CalculateProductScoreResponse',
  full_name='CalculateProductScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='CalculateProductScoreResponse.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='CalculateProductScoreResponse.score', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=510,
)


_ECHOREQUEST = _descriptor.Descriptor(
  name='EchoRequest',
  full_name='EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping', full_name='EchoRequest.ping', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=539,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pong', full_name='EchoResponse.pong', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=569,
)

_UPLOADPRODUCTRESPONSE.fields_by_name['result_status'].enum_type = _UPLOADPRODUCTRESPONSE_RESULTSTATUS
_UPLOADPRODUCTRESPONSE_RESULTSTATUS.containing_type = _UPLOADPRODUCTRESPONSE
_SEARCHPRODUCTSRESPONSE.fields_by_name['products'].message_type = grpc__mate_dot_product__common__pb2._PRODUCT
_CALCULATEPRODUCTSCORERESPONSE.fields_by_name['product'].message_type = grpc__mate_dot_product__common__pb2._PRODUCT
DESCRIPTOR.message_types_by_name['UploadProductResponse'] = _UPLOADPRODUCTRESPONSE
DESCRIPTOR.message_types_by_name['DownloadProductImageRequest'] = _DOWNLOADPRODUCTIMAGEREQUEST
DESCRIPTOR.message_types_by_name['DownloadProductsRequest'] = _DOWNLOADPRODUCTSREQUEST
DESCRIPTOR.message_types_by_name['SearchProductsRequest'] = _SEARCHPRODUCTSREQUEST
DESCRIPTOR.message_types_by_name['SearchProductsResponse'] = _SEARCHPRODUCTSRESPONSE
DESCRIPTOR.message_types_by_name['CalculateProductScoreResponse'] = _CALCULATEPRODUCTSCORERESPONSE
DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadProductResponse = _reflection.GeneratedProtocolMessageType('UploadProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADPRODUCTRESPONSE,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:UploadProductResponse)
  })
_sym_db.RegisterMessage(UploadProductResponse)

DownloadProductImageRequest = _reflection.GeneratedProtocolMessageType('DownloadProductImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADPRODUCTIMAGEREQUEST,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:DownloadProductImageRequest)
  })
_sym_db.RegisterMessage(DownloadProductImageRequest)

DownloadProductsRequest = _reflection.GeneratedProtocolMessageType('DownloadProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADPRODUCTSREQUEST,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:DownloadProductsRequest)
  })
_sym_db.RegisterMessage(DownloadProductsRequest)

SearchProductsRequest = _reflection.GeneratedProtocolMessageType('SearchProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHPRODUCTSREQUEST,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:SearchProductsRequest)
  })
_sym_db.RegisterMessage(SearchProductsRequest)

SearchProductsResponse = _reflection.GeneratedProtocolMessageType('SearchProductsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHPRODUCTSRESPONSE,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:SearchProductsResponse)
  })
_sym_db.RegisterMessage(SearchProductsResponse)

CalculateProductScoreResponse = _reflection.GeneratedProtocolMessageType('CalculateProductScoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEPRODUCTSCORERESPONSE,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:CalculateProductScoreResponse)
  })
_sym_db.RegisterMessage(CalculateProductScoreResponse)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'grpc_mate.product_search_engine_pb2'
  # @@protoc_insertion_point(class_scope:EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)


DESCRIPTOR._options = None

_PRODUCTUPDATESERVICE = _descriptor.ServiceDescriptor(
  name='ProductUpdateService',
  full_name='ProductUpdateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=571,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='UploadProduct',
    full_name='ProductUpdateService.UploadProduct',
    index=0,
    containing_service=None,
    input_type=grpc__mate_dot_product__common__pb2._PRODUCT,
    output_type=_UPLOADPRODUCTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTUPDATESERVICE)

DESCRIPTOR.services_by_name['ProductUpdateService'] = _PRODUCTUPDATESERVICE


_PRODUCTREADSERVICE = _descriptor.ServiceDescriptor(
  name='ProductReadService',
  full_name='ProductReadService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=651,
  serialized_end=943,
  methods=[
  _descriptor.MethodDescriptor(
    name='DownloadProducts',
    full_name='ProductReadService.DownloadProducts',
    index=0,
    containing_service=None,
    input_type=_DOWNLOADPRODUCTSREQUEST,
    output_type=grpc__mate_dot_product__common__pb2._PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchProducts',
    full_name='ProductReadService.SearchProducts',
    index=1,
    containing_service=None,
    input_type=_SEARCHPRODUCTSREQUEST,
    output_type=_SEARCHPRODUCTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CalculateProductScore',
    full_name='ProductReadService.CalculateProductScore',
    index=2,
    containing_service=None,
    input_type=grpc__mate_dot_product__common__pb2._PRODUCT,
    output_type=_CALCULATEPRODUCTSCORERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadProductImage',
    full_name='ProductReadService.DownloadProductImage',
    index=3,
    containing_service=None,
    input_type=_DOWNLOADPRODUCTIMAGEREQUEST,
    output_type=grpc__mate_dot_product__common__pb2._DATACHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTREADSERVICE)

DESCRIPTOR.services_by_name['ProductReadService'] = _PRODUCTREADSERVICE


_ECHOSERVICE = _descriptor.ServiceDescriptor(
  name='EchoService',
  full_name='EchoService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=945,
  serialized_end=1025,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='EchoService.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    serialized_options=_b('\202\323\344\223\002\026\"\021/grpc/api/v1/echo:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHOSERVICE)

DESCRIPTOR.services_by_name['EchoService'] = _ECHOSERVICE

# @@protoc_insertion_point(module_scope)
