apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: elasticsearch-service
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: elasticsearch-service
