sudo: required
language: java
services:
  - docker
before_install: make pull_image
script:
  - make build
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
